// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IdempotentProtocol.proto

package eip.idempotent;

public final class IdempotentProtocol {
  private IdempotentProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class EnvelopeProtocol extends
      com.google.protobuf.GeneratedMessage {
    // Use EnvelopeProtocol.newBuilder() to construct.
    private EnvelopeProtocol() {
      initFields();
    }
    private EnvelopeProtocol(boolean noInit) {}
    
    private static final EnvelopeProtocol defaultInstance;
    public static EnvelopeProtocol getDefaultInstance() {
      return defaultInstance;
    }
    
    public EnvelopeProtocol getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eip.idempotent.IdempotentProtocol.internal_static_eip_idempotent_EnvelopeProtocol_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eip.idempotent.IdempotentProtocol.internal_static_eip_idempotent_EnvelopeProtocol_fieldAccessorTable;
    }
    
    // required int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private long id_ = 0L;
    public boolean hasId() { return hasId; }
    public long getId() { return id_; }
    
    // required int64 timestamp = 2;
    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private boolean hasTimestamp;
    private long timestamp_ = 0L;
    public boolean hasTimestamp() { return hasTimestamp; }
    public long getTimestamp() { return timestamp_; }
    
    // required .eip.idempotent.SenderProtocol sender = 3;
    public static final int SENDER_FIELD_NUMBER = 3;
    private boolean hasSender;
    private eip.idempotent.IdempotentProtocol.SenderProtocol sender_;
    public boolean hasSender() { return hasSender; }
    public eip.idempotent.IdempotentProtocol.SenderProtocol getSender() { return sender_; }
    
    // optional .eip.idempotent.PayloadProtocol payload = 4;
    public static final int PAYLOAD_FIELD_NUMBER = 4;
    private boolean hasPayload;
    private eip.idempotent.IdempotentProtocol.PayloadProtocol payload_;
    public boolean hasPayload() { return hasPayload; }
    public eip.idempotent.IdempotentProtocol.PayloadProtocol getPayload() { return payload_; }
    
    private void initFields() {
      sender_ = eip.idempotent.IdempotentProtocol.SenderProtocol.getDefaultInstance();
      payload_ = eip.idempotent.IdempotentProtocol.PayloadProtocol.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (!hasId) return false;
      if (!hasTimestamp) return false;
      if (!hasSender) return false;
      if (!getSender().isInitialized()) return false;
      if (hasPayload()) {
        if (!getPayload().isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasId()) {
        output.writeInt64(1, getId());
      }
      if (hasTimestamp()) {
        output.writeInt64(2, getTimestamp());
      }
      if (hasSender()) {
        output.writeMessage(3, getSender());
      }
      if (hasPayload()) {
        output.writeMessage(4, getPayload());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, getId());
      }
      if (hasTimestamp()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, getTimestamp());
      }
      if (hasSender()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getSender());
      }
      if (hasPayload()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getPayload());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static eip.idempotent.IdempotentProtocol.EnvelopeProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eip.idempotent.IdempotentProtocol.EnvelopeProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eip.idempotent.IdempotentProtocol.EnvelopeProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eip.idempotent.IdempotentProtocol.EnvelopeProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eip.idempotent.IdempotentProtocol.EnvelopeProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eip.idempotent.IdempotentProtocol.EnvelopeProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static eip.idempotent.IdempotentProtocol.EnvelopeProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eip.idempotent.IdempotentProtocol.EnvelopeProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eip.idempotent.IdempotentProtocol.EnvelopeProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eip.idempotent.IdempotentProtocol.EnvelopeProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eip.idempotent.IdempotentProtocol.EnvelopeProtocol prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private eip.idempotent.IdempotentProtocol.EnvelopeProtocol result;
      
      // Construct using eip.idempotent.IdempotentProtocol.EnvelopeProtocol.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new eip.idempotent.IdempotentProtocol.EnvelopeProtocol();
        return builder;
      }
      
      protected eip.idempotent.IdempotentProtocol.EnvelopeProtocol internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new eip.idempotent.IdempotentProtocol.EnvelopeProtocol();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eip.idempotent.IdempotentProtocol.EnvelopeProtocol.getDescriptor();
      }
      
      public eip.idempotent.IdempotentProtocol.EnvelopeProtocol getDefaultInstanceForType() {
        return eip.idempotent.IdempotentProtocol.EnvelopeProtocol.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public eip.idempotent.IdempotentProtocol.EnvelopeProtocol build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private eip.idempotent.IdempotentProtocol.EnvelopeProtocol buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public eip.idempotent.IdempotentProtocol.EnvelopeProtocol buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        eip.idempotent.IdempotentProtocol.EnvelopeProtocol returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eip.idempotent.IdempotentProtocol.EnvelopeProtocol) {
          return mergeFrom((eip.idempotent.IdempotentProtocol.EnvelopeProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(eip.idempotent.IdempotentProtocol.EnvelopeProtocol other) {
        if (other == eip.idempotent.IdempotentProtocol.EnvelopeProtocol.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasSender()) {
          mergeSender(other.getSender());
        }
        if (other.hasPayload()) {
          mergePayload(other.getPayload());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readInt64());
              break;
            }
            case 16: {
              setTimestamp(input.readInt64());
              break;
            }
            case 26: {
              eip.idempotent.IdempotentProtocol.SenderProtocol.Builder subBuilder = eip.idempotent.IdempotentProtocol.SenderProtocol.newBuilder();
              if (hasSender()) {
                subBuilder.mergeFrom(getSender());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSender(subBuilder.buildPartial());
              break;
            }
            case 34: {
              eip.idempotent.IdempotentProtocol.PayloadProtocol.Builder subBuilder = eip.idempotent.IdempotentProtocol.PayloadProtocol.newBuilder();
              if (hasPayload()) {
                subBuilder.mergeFrom(getPayload());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPayload(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required int64 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public long getId() {
        return result.getId();
      }
      public Builder setId(long value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0L;
        return this;
      }
      
      // required int64 timestamp = 2;
      public boolean hasTimestamp() {
        return result.hasTimestamp();
      }
      public long getTimestamp() {
        return result.getTimestamp();
      }
      public Builder setTimestamp(long value) {
        result.hasTimestamp = true;
        result.timestamp_ = value;
        return this;
      }
      public Builder clearTimestamp() {
        result.hasTimestamp = false;
        result.timestamp_ = 0L;
        return this;
      }
      
      // required .eip.idempotent.SenderProtocol sender = 3;
      public boolean hasSender() {
        return result.hasSender();
      }
      public eip.idempotent.IdempotentProtocol.SenderProtocol getSender() {
        return result.getSender();
      }
      public Builder setSender(eip.idempotent.IdempotentProtocol.SenderProtocol value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasSender = true;
        result.sender_ = value;
        return this;
      }
      public Builder setSender(eip.idempotent.IdempotentProtocol.SenderProtocol.Builder builderForValue) {
        result.hasSender = true;
        result.sender_ = builderForValue.build();
        return this;
      }
      public Builder mergeSender(eip.idempotent.IdempotentProtocol.SenderProtocol value) {
        if (result.hasSender() &&
            result.sender_ != eip.idempotent.IdempotentProtocol.SenderProtocol.getDefaultInstance()) {
          result.sender_ =
            eip.idempotent.IdempotentProtocol.SenderProtocol.newBuilder(result.sender_).mergeFrom(value).buildPartial();
        } else {
          result.sender_ = value;
        }
        result.hasSender = true;
        return this;
      }
      public Builder clearSender() {
        result.hasSender = false;
        result.sender_ = eip.idempotent.IdempotentProtocol.SenderProtocol.getDefaultInstance();
        return this;
      }
      
      // optional .eip.idempotent.PayloadProtocol payload = 4;
      public boolean hasPayload() {
        return result.hasPayload();
      }
      public eip.idempotent.IdempotentProtocol.PayloadProtocol getPayload() {
        return result.getPayload();
      }
      public Builder setPayload(eip.idempotent.IdempotentProtocol.PayloadProtocol value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasPayload = true;
        result.payload_ = value;
        return this;
      }
      public Builder setPayload(eip.idempotent.IdempotentProtocol.PayloadProtocol.Builder builderForValue) {
        result.hasPayload = true;
        result.payload_ = builderForValue.build();
        return this;
      }
      public Builder mergePayload(eip.idempotent.IdempotentProtocol.PayloadProtocol value) {
        if (result.hasPayload() &&
            result.payload_ != eip.idempotent.IdempotentProtocol.PayloadProtocol.getDefaultInstance()) {
          result.payload_ =
            eip.idempotent.IdempotentProtocol.PayloadProtocol.newBuilder(result.payload_).mergeFrom(value).buildPartial();
        } else {
          result.payload_ = value;
        }
        result.hasPayload = true;
        return this;
      }
      public Builder clearPayload() {
        result.hasPayload = false;
        result.payload_ = eip.idempotent.IdempotentProtocol.PayloadProtocol.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:eip.idempotent.EnvelopeProtocol)
    }
    
    static {
      defaultInstance = new EnvelopeProtocol(true);
      eip.idempotent.IdempotentProtocol.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:eip.idempotent.EnvelopeProtocol)
  }
  
  public static final class SenderProtocol extends
      com.google.protobuf.GeneratedMessage {
    // Use SenderProtocol.newBuilder() to construct.
    private SenderProtocol() {
      initFields();
    }
    private SenderProtocol(boolean noInit) {}
    
    private static final SenderProtocol defaultInstance;
    public static SenderProtocol getDefaultInstance() {
      return defaultInstance;
    }
    
    public SenderProtocol getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eip.idempotent.IdempotentProtocol.internal_static_eip_idempotent_SenderProtocol_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eip.idempotent.IdempotentProtocol.internal_static_eip_idempotent_SenderProtocol_fieldAccessorTable;
    }
    
    // required string host = 1;
    public static final int HOST_FIELD_NUMBER = 1;
    private boolean hasHost;
    private java.lang.String host_ = "";
    public boolean hasHost() { return hasHost; }
    public java.lang.String getHost() { return host_; }
    
    // required int32 port = 2;
    public static final int PORT_FIELD_NUMBER = 2;
    private boolean hasPort;
    private int port_ = 0;
    public boolean hasPort() { return hasPort; }
    public int getPort() { return port_; }
    
    // required string actor = 3;
    public static final int ACTOR_FIELD_NUMBER = 3;
    private boolean hasActor;
    private java.lang.String actor_ = "";
    public boolean hasActor() { return hasActor; }
    public java.lang.String getActor() { return actor_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasHost) return false;
      if (!hasPort) return false;
      if (!hasActor) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasHost()) {
        output.writeString(1, getHost());
      }
      if (hasPort()) {
        output.writeInt32(2, getPort());
      }
      if (hasActor()) {
        output.writeString(3, getActor());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasHost()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getHost());
      }
      if (hasPort()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getPort());
      }
      if (hasActor()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getActor());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static eip.idempotent.IdempotentProtocol.SenderProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eip.idempotent.IdempotentProtocol.SenderProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eip.idempotent.IdempotentProtocol.SenderProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eip.idempotent.IdempotentProtocol.SenderProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eip.idempotent.IdempotentProtocol.SenderProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eip.idempotent.IdempotentProtocol.SenderProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static eip.idempotent.IdempotentProtocol.SenderProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eip.idempotent.IdempotentProtocol.SenderProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eip.idempotent.IdempotentProtocol.SenderProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eip.idempotent.IdempotentProtocol.SenderProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eip.idempotent.IdempotentProtocol.SenderProtocol prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private eip.idempotent.IdempotentProtocol.SenderProtocol result;
      
      // Construct using eip.idempotent.IdempotentProtocol.SenderProtocol.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new eip.idempotent.IdempotentProtocol.SenderProtocol();
        return builder;
      }
      
      protected eip.idempotent.IdempotentProtocol.SenderProtocol internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new eip.idempotent.IdempotentProtocol.SenderProtocol();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eip.idempotent.IdempotentProtocol.SenderProtocol.getDescriptor();
      }
      
      public eip.idempotent.IdempotentProtocol.SenderProtocol getDefaultInstanceForType() {
        return eip.idempotent.IdempotentProtocol.SenderProtocol.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public eip.idempotent.IdempotentProtocol.SenderProtocol build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private eip.idempotent.IdempotentProtocol.SenderProtocol buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public eip.idempotent.IdempotentProtocol.SenderProtocol buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        eip.idempotent.IdempotentProtocol.SenderProtocol returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eip.idempotent.IdempotentProtocol.SenderProtocol) {
          return mergeFrom((eip.idempotent.IdempotentProtocol.SenderProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(eip.idempotent.IdempotentProtocol.SenderProtocol other) {
        if (other == eip.idempotent.IdempotentProtocol.SenderProtocol.getDefaultInstance()) return this;
        if (other.hasHost()) {
          setHost(other.getHost());
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        if (other.hasActor()) {
          setActor(other.getActor());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setHost(input.readString());
              break;
            }
            case 16: {
              setPort(input.readInt32());
              break;
            }
            case 26: {
              setActor(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string host = 1;
      public boolean hasHost() {
        return result.hasHost();
      }
      public java.lang.String getHost() {
        return result.getHost();
      }
      public Builder setHost(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasHost = true;
        result.host_ = value;
        return this;
      }
      public Builder clearHost() {
        result.hasHost = false;
        result.host_ = getDefaultInstance().getHost();
        return this;
      }
      
      // required int32 port = 2;
      public boolean hasPort() {
        return result.hasPort();
      }
      public int getPort() {
        return result.getPort();
      }
      public Builder setPort(int value) {
        result.hasPort = true;
        result.port_ = value;
        return this;
      }
      public Builder clearPort() {
        result.hasPort = false;
        result.port_ = 0;
        return this;
      }
      
      // required string actor = 3;
      public boolean hasActor() {
        return result.hasActor();
      }
      public java.lang.String getActor() {
        return result.getActor();
      }
      public Builder setActor(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasActor = true;
        result.actor_ = value;
        return this;
      }
      public Builder clearActor() {
        result.hasActor = false;
        result.actor_ = getDefaultInstance().getActor();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:eip.idempotent.SenderProtocol)
    }
    
    static {
      defaultInstance = new SenderProtocol(true);
      eip.idempotent.IdempotentProtocol.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:eip.idempotent.SenderProtocol)
  }
  
  public static final class PayloadProtocol extends
      com.google.protobuf.GeneratedMessage {
    // Use PayloadProtocol.newBuilder() to construct.
    private PayloadProtocol() {
      initFields();
    }
    private PayloadProtocol(boolean noInit) {}
    
    private static final PayloadProtocol defaultInstance;
    public static PayloadProtocol getDefaultInstance() {
      return defaultInstance;
    }
    
    public PayloadProtocol getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eip.idempotent.IdempotentProtocol.internal_static_eip_idempotent_PayloadProtocol_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eip.idempotent.IdempotentProtocol.internal_static_eip_idempotent_PayloadProtocol_fieldAccessorTable;
    }
    
    // required bytes message = 1;
    public static final int MESSAGE_FIELD_NUMBER = 1;
    private boolean hasMessage;
    private com.google.protobuf.ByteString message_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasMessage() { return hasMessage; }
    public com.google.protobuf.ByteString getMessage() { return message_; }
    
    // optional bytes messageManifest = 2;
    public static final int MESSAGEMANIFEST_FIELD_NUMBER = 2;
    private boolean hasMessageManifest;
    private com.google.protobuf.ByteString messageManifest_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasMessageManifest() { return hasMessageManifest; }
    public com.google.protobuf.ByteString getMessageManifest() { return messageManifest_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasMessage) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasMessage()) {
        output.writeBytes(1, getMessage());
      }
      if (hasMessageManifest()) {
        output.writeBytes(2, getMessageManifest());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasMessage()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMessage());
      }
      if (hasMessageManifest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMessageManifest());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static eip.idempotent.IdempotentProtocol.PayloadProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eip.idempotent.IdempotentProtocol.PayloadProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eip.idempotent.IdempotentProtocol.PayloadProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eip.idempotent.IdempotentProtocol.PayloadProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eip.idempotent.IdempotentProtocol.PayloadProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eip.idempotent.IdempotentProtocol.PayloadProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static eip.idempotent.IdempotentProtocol.PayloadProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eip.idempotent.IdempotentProtocol.PayloadProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eip.idempotent.IdempotentProtocol.PayloadProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eip.idempotent.IdempotentProtocol.PayloadProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eip.idempotent.IdempotentProtocol.PayloadProtocol prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private eip.idempotent.IdempotentProtocol.PayloadProtocol result;
      
      // Construct using eip.idempotent.IdempotentProtocol.PayloadProtocol.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new eip.idempotent.IdempotentProtocol.PayloadProtocol();
        return builder;
      }
      
      protected eip.idempotent.IdempotentProtocol.PayloadProtocol internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new eip.idempotent.IdempotentProtocol.PayloadProtocol();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eip.idempotent.IdempotentProtocol.PayloadProtocol.getDescriptor();
      }
      
      public eip.idempotent.IdempotentProtocol.PayloadProtocol getDefaultInstanceForType() {
        return eip.idempotent.IdempotentProtocol.PayloadProtocol.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public eip.idempotent.IdempotentProtocol.PayloadProtocol build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private eip.idempotent.IdempotentProtocol.PayloadProtocol buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public eip.idempotent.IdempotentProtocol.PayloadProtocol buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        eip.idempotent.IdempotentProtocol.PayloadProtocol returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eip.idempotent.IdempotentProtocol.PayloadProtocol) {
          return mergeFrom((eip.idempotent.IdempotentProtocol.PayloadProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(eip.idempotent.IdempotentProtocol.PayloadProtocol other) {
        if (other == eip.idempotent.IdempotentProtocol.PayloadProtocol.getDefaultInstance()) return this;
        if (other.hasMessage()) {
          setMessage(other.getMessage());
        }
        if (other.hasMessageManifest()) {
          setMessageManifest(other.getMessageManifest());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setMessage(input.readBytes());
              break;
            }
            case 18: {
              setMessageManifest(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // required bytes message = 1;
      public boolean hasMessage() {
        return result.hasMessage();
      }
      public com.google.protobuf.ByteString getMessage() {
        return result.getMessage();
      }
      public Builder setMessage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMessage = true;
        result.message_ = value;
        return this;
      }
      public Builder clearMessage() {
        result.hasMessage = false;
        result.message_ = getDefaultInstance().getMessage();
        return this;
      }
      
      // optional bytes messageManifest = 2;
      public boolean hasMessageManifest() {
        return result.hasMessageManifest();
      }
      public com.google.protobuf.ByteString getMessageManifest() {
        return result.getMessageManifest();
      }
      public Builder setMessageManifest(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMessageManifest = true;
        result.messageManifest_ = value;
        return this;
      }
      public Builder clearMessageManifest() {
        result.hasMessageManifest = false;
        result.messageManifest_ = getDefaultInstance().getMessageManifest();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:eip.idempotent.PayloadProtocol)
    }
    
    static {
      defaultInstance = new PayloadProtocol(true);
      eip.idempotent.IdempotentProtocol.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:eip.idempotent.PayloadProtocol)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_eip_idempotent_EnvelopeProtocol_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eip_idempotent_EnvelopeProtocol_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_eip_idempotent_SenderProtocol_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eip_idempotent_SenderProtocol_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_eip_idempotent_PayloadProtocol_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eip_idempotent_PayloadProtocol_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030IdempotentProtocol.proto\022\016eip.idempote" +
      "nt\"\223\001\n\020EnvelopeProtocol\022\n\n\002id\030\001 \002(\003\022\021\n\tt" +
      "imestamp\030\002 \002(\003\022.\n\006sender\030\003 \002(\0132\036.eip.ide" +
      "mpotent.SenderProtocol\0220\n\007payload\030\004 \001(\0132" +
      "\037.eip.idempotent.PayloadProtocol\";\n\016Send" +
      "erProtocol\022\014\n\004host\030\001 \002(\t\022\014\n\004port\030\002 \002(\005\022\r" +
      "\n\005actor\030\003 \002(\t\";\n\017PayloadProtocol\022\017\n\007mess" +
      "age\030\001 \002(\014\022\027\n\017messageManifest\030\002 \001(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_eip_idempotent_EnvelopeProtocol_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_eip_idempotent_EnvelopeProtocol_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_eip_idempotent_EnvelopeProtocol_descriptor,
              new java.lang.String[] { "Id", "Timestamp", "Sender", "Payload", },
              eip.idempotent.IdempotentProtocol.EnvelopeProtocol.class,
              eip.idempotent.IdempotentProtocol.EnvelopeProtocol.Builder.class);
          internal_static_eip_idempotent_SenderProtocol_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_eip_idempotent_SenderProtocol_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_eip_idempotent_SenderProtocol_descriptor,
              new java.lang.String[] { "Host", "Port", "Actor", },
              eip.idempotent.IdempotentProtocol.SenderProtocol.class,
              eip.idempotent.IdempotentProtocol.SenderProtocol.Builder.class);
          internal_static_eip_idempotent_PayloadProtocol_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_eip_idempotent_PayloadProtocol_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_eip_idempotent_PayloadProtocol_descriptor,
              new java.lang.String[] { "Message", "MessageManifest", },
              eip.idempotent.IdempotentProtocol.PayloadProtocol.class,
              eip.idempotent.IdempotentProtocol.PayloadProtocol.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
